# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('horas', models.PositiveIntegerField()),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('zona', models.CharField(max_length=50)),
                ('target', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
            ],
        ),
    ]
