# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('remuneracion', models.PositiveIntegerField()),
                ('horas_semana', models.PositiveIntegerField()),
                ('dias_trabajo', models.PositiveIntegerField()),
                ('zona', models.CharField(max_length=50)),
                ('target', models.TextField()),
                ('duracion', models.PositiveIntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
            ],
        ),
    ]
