/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculadora;

import java.awt.event.KeyEvent;

/**
 *
 * @author i42seged
 */



public class Calculadora extends javax.swing.JFrame {
    private double left_operator;
    boolean operation;
    char OPERATOR;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
	left_operator=Double.POSITIVE_INFINITY;
	operation=false;
	OPERATOR=' ';
	initComponents();
    }
    private double operar(double right_operator){
	double result=left_operator;
	switch(OPERATOR){
	   case '+':
		result=left_operator + right_operator;
		break;
	   case '-':
		result=left_operator - right_operator;
		break;
	   case '*':
	       result=left_operator * right_operator;
		break;
	   case '/':
	       if(right_operator!=0){
		   result=left_operator/right_operator;
	       }else{
		   popUp.infoBox("No puede dividir entre 0", "Error");
		   left_operator=Double.POSITIVE_INFINITY;
		   operation=false;
		   OPERATOR=' ';
		   result=left_operator;
	       }
		break;
	}
	OPERATOR=' ';
	return result;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora-David Serrano Gemes");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                licked(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setToolTipText("");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.GridLayout(5, 0, 0, 25));

        jButton15.setText("+");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jPanel3.add(jButton15);

        jButton17.setText("-");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        jPanel3.add(jButton17);

        jButton16.setText("*");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jPanel3.add(jButton16);

        jButton14.setText("/");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jPanel3.add(jButton14);

        jButton18.setText("=");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jPanel3.add(jButton18);

        jPanel4.setLayout(new java.awt.GridLayout(3, 3, 3, 3));

        jButton1.setText("1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton2.setText("2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton3.setText("3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel4.add(jButton3);

        jButton4.setText("4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton5.setText("5");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel4.add(jButton5);

        jButton6.setText("6");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel4.add(jButton6);

        jButton7.setText("7");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel4.add(jButton7);

        jButton8.setText("8");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel4.add(jButton8);

        jButton9.setText("9");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel4.add(jButton9);

        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        jButton13.setText("0");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jPanel2.add(jButton13);

        jButton12.setText(".");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jPanel2.add(jButton12);

        jButton11.setText("AC");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel2.add(jButton11);

        jButton10.setText("<-");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel2.add(jButton10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
	String aux;
	if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"1";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
	String aux;
	if(operation){
		jTextField1.setText("");
		operation=false;
    }
	aux=jTextField1.getText();
	aux=aux+"2";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
	String aux;
	if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"3";
	jTextField1.setText(aux);
	jTextField1.requestFocus();

    }//GEN-LAST:event_jButton3MouseClicked

    private void licked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_licked
        // TODO add your handling code here:
    }//GEN-LAST:event_licked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String aux;
	if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"4";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
	String aux;
	if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"5";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        String aux;
	if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"6";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        String aux;
	if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"7";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        String aux;
	if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"8";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
       String aux;
       if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"9";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // SUMA
	String aux;
	aux=jTextField1.getText();
	//aux=aux+"+";
	if(aux.length()>0){
	    operation=true;
	    if(left_operator==Double.POSITIVE_INFINITY){
		left_operator=Double.parseDouble(aux);
		OPERATOR='+';
	    }else{
		left_operator=operar(Double.parseDouble(aux));
		OPERATOR='+';
	    }
	    if(left_operator==Double.POSITIVE_INFINITY){
		jTextField1.setText("");
	    }else{
		aux=String.valueOf(left_operator);
		jTextField1.setText(aux);

	    }
	}
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        String aux;
	if(operation){
	    jTextField1.setText("");
	    operation=false;
	}
	aux=jTextField1.getText();
	aux=aux+"0";
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
	// .
	String aux;
	aux=jTextField1.getText();
        
	Boolean check=false;
	for(int i=0;i<aux.length();i++){
	    if(aux.charAt(i)=='.'){
		check=true;
	    }
	}
	if(!check && aux.length()>0){
	   aux=aux+".";
	   
	}
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
	//Clean
	jTextField1.setText("");
	operation=false;
	left_operator=Double.POSITIVE_INFINITY;
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // Eliminar ultimo caracter
	String aux;
	aux=jTextField1.getText();
	
	if (aux!=null && aux.length()>0) {
	    aux=aux.substring(0,aux.length()-1);
	}
	jTextField1.setText(aux);
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        // TODO add your handling code here:
	 // Resta
	String aux;
	aux=jTextField1.getText();
	//aux=aux+"+";
	if(aux.length()>0){
	    operation=true;
	    if(left_operator==Double.POSITIVE_INFINITY){
		left_operator=Double.parseDouble(aux);
		OPERATOR='-';
	    }else{
		left_operator=operar(Double.parseDouble(aux));
	        OPERATOR='-';
	    }
	    if(left_operator==Double.POSITIVE_INFINITY){
		jTextField1.setText("");
	    }else{
		aux=String.valueOf(left_operator);
		jTextField1.setText(aux);
	    }
	}
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // TODO add your handling code here:
	String aux;
	aux=jTextField1.getText();
	//aux=aux+"+";
	if(aux.length()>0){
	    operation=true;
	    if(left_operator==Double.POSITIVE_INFINITY){
		left_operator=Double.parseDouble(aux);
	    }else{
		left_operator=operar(Double.parseDouble(aux));
		OPERATOR=' ';
	    }
	    if(left_operator==Double.POSITIVE_INFINITY){
		jTextField1.setText("");
	    }else{
		aux=String.valueOf(left_operator);
		jTextField1.setText(aux);

	    }
	}
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
	String aux;
	aux=jTextField1.getText();
	//aux=aux+"+";
	if(aux.length()>0){
	    operation=true;
	    if(left_operator==Double.POSITIVE_INFINITY){
		left_operator=Double.parseDouble(aux);
		OPERATOR='*';
	    }else{
		left_operator=operar(Double.parseDouble(aux));
		OPERATOR='*';
	    }
	    if(left_operator==Double.POSITIVE_INFINITY){
		jTextField1.setText("");
	    }else{
		aux=String.valueOf(left_operator);
		jTextField1.setText(aux);
	    }
	}
	jTextField1.requestFocus();
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
		String aux;
	aux=jTextField1.getText();
	//aux=aux+"+";
	if(aux.length()>0){
	    operation=true;
	    if(left_operator==Double.POSITIVE_INFINITY){
		left_operator=Double.parseDouble(aux);
		OPERATOR='/';
	    }else{
		left_operator=operar(Double.parseDouble(aux));
		OPERATOR='/';
	    }
	    if(left_operator==Double.POSITIVE_INFINITY){
		jTextField1.setText("");
	    }else{
		aux=String.valueOf(left_operator);
		jTextField1.setText(aux);
	    }
	}
	jTextField1.requestFocus();

    }//GEN-LAST:event_jButton14MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
	int keyCode = evt.getKeyCode();
      switch( keyCode ) {
	   case KeyEvent.VK_NUMPAD0:
	   case KeyEvent.VK_0:
		jButton13MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD1:
	   case KeyEvent.VK_1:
		jButton1MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD2:
	   case KeyEvent.VK_2:
		jButton2MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD3:
	   case KeyEvent.VK_3 :
		jButton3MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD4:
	   case KeyEvent.VK_4 :
		jButton4MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD5:
           case KeyEvent.VK_5 :
		jButton5MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD6:
           case KeyEvent.VK_6 :
		jButton6MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD7:
           case KeyEvent.VK_7 :
		jButton7MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD8:
           case KeyEvent.VK_8 :
		jButton8MouseClicked(null);
		break;

	   case KeyEvent.VK_NUMPAD9:
           case KeyEvent.VK_9 :
		jButton9MouseClicked(null);
		break;

	   case KeyEvent.VK_ADD:
	   case KeyEvent.VK_PLUS:
		jButton15MouseClicked(null);
		break;

	   case KeyEvent.VK_SUBTRACT:
	   case KeyEvent.VK_MINUS:
		jButton17MouseClicked(null);
		break;

	   case KeyEvent.VK_MULTIPLY:
	  // case KeyEvent.VK_:
		jButton16MouseClicked(null);
		break;

	   case KeyEvent.VK_DIVIDE:
		jButton14MouseClicked(null);
		break;

	   case KeyEvent.VK_DECIMAL:
		jButton12MouseClicked(null);
		break;

	   case KeyEvent.VK_ESCAPE:
		jButton11MouseClicked(null);
		break;

	   case KeyEvent.VK_ENTER:
	  // case KeyEvent.VK_:
		jButton18MouseClicked(null);
		break;

	   case KeyEvent.VK_BACK_SPACE:
	   case KeyEvent.VK_DELETE:
	  // case KeyEvent.VK_:
		jButton10MouseClicked(null);
		break;
	}
	jTextField1.requestFocus();
    }//GEN-LAST:event_jTextField1KeyPressed
                               
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Calculadora().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
