/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package simon_dice;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
/**
 *
 * @author i42seged
 */
public class simon_dice extends javax.swing.JPanel {

    /**
     * Creates new form simon_dice
     */
    List objetivo;
    int nivel;
    int puntuacion;
    Boolean partida_empezada;
    
    public simon_dice() {
	initComponents();
	objetivo = new ArrayList();
	nivel=6;
	puntuacion=0;
	partida_empezada=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("Mostrar paso");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simon_dice/images/red_base.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simon_dice/images/yellow_base.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simon_dice/images/blue_base.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simon_dice/images/green_base.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jButton3.setText("jButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        pulsed("red");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
	pulsed("yellow");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
	pulsed("green");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
	pulsed("blue");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
	//Start button
	if(partida_empezada){
	    System.out.println("DEBUG. la partida esta empezada");
	}else{
	    partida_empezada=true;
	    generar_secuencia();
	    mostrar_secuencia();
	    try {
	    	    TimeUnit.SECONDS.sleep(5);
	    } catch (InterruptedException ex) {
		Logger.getLogger(simon_dice.class.getName()).log(Level.SEVERE, null, ex);
	    }
	   	    System.out.println("TARDA");

	}
    }//GEN-LAST:event_jButton1MouseClicked

	void generar_secuencia(){
	    Random randomGenerator = new Random();
	    for(int i=0;i<nivel;i++){
		int valor=randomGenerator.nextInt(4);
		objetivo.add(valor);
	    }
	}
	void mostrar_secuencia(){
	    for(int i=0;i<objetivo.size();i++){
		int indice = (int) objetivo.get(i);
		switch(indice){
		    case 0:
			pulsed("rojo");
			break;
		    
		    case 1:
			pulsed("amarillo");
			break;
			
		    case 2:
			pulsed("azul");
			break;
			
		    case 3:
			pulsed("verde");
			break;
		}
	    }
	}
    
	
	Boolean pulsed(String button){
	    //Cambia el color del boton momentaneamente
	    ImageIcon icon;
	    URL resource = null;
	    if(button.equals("rojo")){
		resource = getClass().getResource("/simon_dice/images/red_ilu.png");
		icon = new ImageIcon(resource);
		jLabel1.setIcon(icon);
		SwingUtilities.updateComponentTreeUI(jLabel1);
	    }
	    if(button.equals("amarillo")){
		resource = getClass().getResource("/simon_dice/images/yellow_ilu.png");
		icon = new ImageIcon(resource);
		jLabel2.setIcon(icon);
		SwingUtilities.updateComponentTreeUI(jLabel2);
	    }
	    if(button.equals("verde")){
		resource = getClass().getResource("/simon_dice/images/green_ilu.png");
		icon = new ImageIcon(resource);
		jLabel4.setIcon(icon);
		SwingUtilities.updateComponentTreeUI(jLabel4);

	    }
	    if(button.equals("azul")){
		resource = getClass().getResource("/simon_dice/images/blue_ilu.png");
		icon = new ImageIcon(resource);
		jLabel3.setIcon(icon);
		SwingUtilities.updateComponentTreeUI(jLabel3);

	    }
	    try {
	    	    TimeUnit.SECONDS.sleep(1);
	    } catch (InterruptedException ex) {
		Logger.getLogger(simon_dice.class.getName()).log(Level.SEVERE, null, ex);
	    }
	/*    if(button.equals("rojo")){
		resource = getClass().getResource("/simon_dice/images/red_base.png");
		icon = new ImageIcon(resource);
		jLabel1.setIcon(icon);
	    }
	    if(button.equals("amarillo")){
		resource = getClass().getResource("/simon_dice/images/yellow_base.png");
		icon = new ImageIcon(resource);
		jLabel2.setIcon(icon);
	    }
	    if(button.equals("verde")){
		resource = getClass().getResource("/simon_dice/images/green_base.png");
		icon = new ImageIcon(resource);
		jLabel4.setIcon(icon);
	    }
	    if(button.equals("azul")){
		resource = getClass().getResource("/simon_dice/images/blue_base.png");
		icon = new ImageIcon(resource);
		jLabel3.setIcon(icon);
	    }
		*/ 
	    	    System.out.println(button);
	    return true;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
