/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package internacionalizacion_p4;

import java.util.Locale;
import java.util.ResourceBundle;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author i42seged
 */
public class internacionalizacion_p4 extends javax.swing.JFrame {

    /**
     * Creates new form internacionalizacion_p4
     */
    
    String Lang;
    public internacionalizacion_p4() {
	initComponents();
	Lang="EN";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("internacionalizacion_p4/Bundle"); // NOI18N
        setTitle(bundle.getString("internacionalizacion_p4.title")); // NOI18N

        jTextField1.setText(bundle.getString("internacionalizacion_p4.jTextField1.text")); // NOI18N

        jTextField2.setText(bundle.getString("internacionalizacion_p4.jTextField2.text")); // NOI18N

        jLabel1.setText(bundle.getString("internacionalizacion_p4.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("internacionalizacion_p4.jLabel2.text")); // NOI18N

        jTextField3.setText(bundle.getString("internacionalizacion_p4.jTextField3.text")); // NOI18N

        jLabel3.setText(bundle.getString("internacionalizacion_p4.jLabel3.text")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internacionalizacion_p4/Bandera-españa.png"))); // NOI18N
        jButton1.setText(bundle.getString("internacionalizacion_p4.jButton1.text")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internacionalizacion_p4/Bandera_Gran_Bretaña.png"))); // NOI18N
        jButton2.setText(bundle.getString("internacionalizacion_p4.jButton2.text")); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeLanguaje(String Language){
	if(!Language.equals(Lang)){
	   Locale currentLocale;
	   ResourceBundle bundle;
	   String LastLang=Lang;
	   switch(Language){
		case"ES":
		   Lang="ES";
		   currentLocale = new Locale("es","ES");
		   this.setTitle("Internacionalización");
		   break;
		case"EN":
		   Lang="EN";
		   currentLocale = new Locale("en","GB");
		   this.setTitle("Internacionalization");
		   break;
		default:
		   Lang="EN";
		   this.setTitle("Internacionalization");
		   currentLocale = new Locale("en","GB");
	   }
	   bundle= ResourceBundle.getBundle("internacionalizacion_p4/Bundle",currentLocale);

	   jLabel1.setText(bundle.getString("internacionalizacion_p4.jLabel1.text"));
	   changeNumber(LastLang);
	   
	   jLabel2.setText(bundle.getString("internacionalizacion_p4.jLabel2.text"));
	   changeCurrency(LastLang);
	   
	   jLabel3.setText(bundle.getString("internacionalizacion_p4.jLabel3.text"));
	   changeDate(LastLang);
	   
	}
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       if(!("ES".equals(Lang))){
	   changeLanguaje("ES");
	}
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(!("EN".equals(Lang))){
	   changeLanguaje("EN");
	}
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(internacionalizacion_p4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(internacionalizacion_p4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(internacionalizacion_p4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(internacionalizacion_p4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new internacionalizacion_p4().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void changeNumber(String LastLang) {
	String aux;
   	switch(Lang){
		case"ES":
			
		   aux=jTextField1.getText();
		   if(LastLang.equals("EN")){
		       aux=aux.replace(',', '|');
		       aux=aux.replace('.', ',');
		       aux=aux.replace('|', '.');

		       jTextField1.setText(aux);
		   }
		    
		    
		   break;
		case"EN":
		   aux=jTextField1.getText();
		   if(LastLang.equals("ES")){
		       aux=aux.replace('.', '|');
		       aux=aux.replace(',', '.');
		       aux=aux.replace('|', ',');
		       jTextField1.setText(aux);
		   }
		   break;
	   }
    }

    private void changeCurrency(String LastLang) {
	String aux;
	
	char[] charArray;
	int lenght;
	char currency;
	aux=jTextField2.getText();
	char[] charArrayReturn;
	
	aux= jTextField2.getText();
        /*Pattern p;
         Matcher m;*/
	switch(Lang){
		case"ES":
		    if(LastLang.equals("EN")){
			   // System.out.println(aux);
			    currency='£';
			    if(aux.indexOf(currency)<0){
				//lenght--;
				aux="£"+aux;
			    }
			    lenght=aux.length();
			    charArrayReturn=aux.toCharArray();
			    charArray = aux.toCharArray();
			    for(int i=0,j=0;i<lenght;i++){
				if(charArray[i]!=currency){
				    if(charArray[i]=='.'){
					charArrayReturn[j]=',';
				    }else if(charArray[i]==','){
					charArrayReturn[j]='.';
				    }else{
					charArrayReturn[j]=charArray[i];
					
				    }
				    j++;
				}
			    }
			    charArrayReturn[lenght-1]='€';
  			    aux=String.valueOf(charArrayReturn);

			    //System.out.println(aux);
			    jTextField2.setText(aux);
			 }
			 
		   break;
		case"EN":
		  if(LastLang.equals("ES")){
			    //System.out.println(aux);
			    currency='€';
			    if(aux.indexOf(currency)<0){
				//lenght--;
				aux=aux+"€";
			    }
			    lenght=aux.length();
			    charArrayReturn=aux.toCharArray();
			    charArray = aux.toCharArray();
       			    charArrayReturn[0]='£';

			    for(int i=0,j=1;i<lenght;i++){
				if(charArray[i]!=currency){
				    if(charArray[i]=='.'){
					charArrayReturn[j]=',';
				    }else if(charArray[i]==','){
					charArrayReturn[j]='.';
				    }else{
					charArrayReturn[j]=charArray[i];
					
				    }
				    j++;
				}
			    }
			    aux=String.valueOf(charArrayReturn);
			    //System.out.println(aux);

			    jTextField2.setText(aux);
			 }
			 
		   break;
	   }
    }

    private void changeDate(String LastLang) {
        String aux;
        aux= jTextField3.getText();
        Pattern p;
        p = Pattern.compile("([0-9]{1,2})[/|-]([0-9]{1,2})[/|-]([0-9]{4})");
        Matcher m = p.matcher(aux);
        
        switch(Lang){
            case"ES":
                if(m.find()){
                    aux=m.group(2)+"/"+m.group(1)+"/"+m.group(3);
                    jTextField3.setText(aux);
                      
                }else{
		 jTextField3.setText("DIA/MES/AÑO");
                }
                break;
            case"EN":
                if(m.find()){
                    aux=m.group(2)+"/"+m.group(1)+"/"+m.group(3);
                    jTextField3.setText(aux);
                      
                }else{
                  jTextField3.setText("MONTH/DAY/YEAR");
                }
                
                break;
            default:
                
                
             
        }
        
    }
}
